name: validate

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      # TODO caching https://github.com/actions/setup-java#caching-packages-dependencies
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Install lein
        run: brew install leiningen

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: "~/.m2/repository"
          key: ${{ runner.os }}-${{ hashFiles('project.clj') }}
      - name: Run clj tests
        run: lein test
      - name: Run cljs tests
        run: lein doo

